export const MICROSERVICES_CLIENTS = {
    ORDERS_SERVICE: 'ORDERS_SERVICE',
    //PAYMENTS_SERVICE: 'PAYMENTS_SERVICE',
    PRODUCTS_SERVICE: 'PRODUCTS_SERVICE',
    USERS_SERVICE: 'USERS_SERVICE',
}